server:
  port: ${SERVER_PORT:20800}

spring:
  application:
    name: mom-integration-server
  cloud:
    nacos:
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:false}
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        cluster-name: ${NACOS_CLUSTER_NAME:DEFAULT}
    openfeign:
      client:
        config:
          mom-mdm-server:
            connect-timeout: ${MDM_CLIENT_CONNECT_TIMEOUT:2000}
            read-timeout: ${MDM_CLIENT_READ_TIMEOUT:3000}
            logger-level: basic

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,nacos-discovery
  endpoint:
    health:
      probes:
        enabled: true
