-- MDM V1 统一使用人类可读的通用名称；多语言名称由未来独立翻译表承载。
ALTER TABLE mdm_plant RENAME COLUMN name_zh TO name;
ALTER TABLE mdm_plant DROP COLUMN name_en;
ALTER TABLE mdm_workshop RENAME COLUMN name_zh TO name;
ALTER TABLE mdm_workshop DROP COLUMN name_en;
ALTER TABLE mdm_production_line RENAME COLUMN name_zh TO name;
ALTER TABLE mdm_production_line DROP COLUMN name_en;
ALTER TABLE mdm_workstation RENAME COLUMN name_zh TO name;
ALTER TABLE mdm_workstation DROP COLUMN name_en;
ALTER TABLE mdm_warehouse RENAME COLUMN name_zh TO name;
ALTER TABLE mdm_warehouse DROP COLUMN name_en;
ALTER TABLE mdm_warehouse_area RENAME COLUMN name_zh TO name;
ALTER TABLE mdm_warehouse_area DROP COLUMN name_en;
ALTER TABLE mdm_location_type RENAME COLUMN name_zh TO name;
ALTER TABLE mdm_location_type DROP COLUMN name_en;
ALTER TABLE mdm_location RENAME COLUMN name_zh TO name;
ALTER TABLE mdm_location DROP COLUMN name_en;
ALTER TABLE mdm_material_category RENAME COLUMN name_zh TO name;
ALTER TABLE mdm_material_category DROP COLUMN name_en;
ALTER TABLE mdm_material_category DROP COLUMN default_batch_managed;
ALTER TABLE mdm_dimension RENAME COLUMN name_zh TO name;
ALTER TABLE mdm_dimension DROP COLUMN name_en;
ALTER TABLE mdm_uom_category RENAME COLUMN name_zh TO name;
ALTER TABLE mdm_uom_category DROP COLUMN name_en;
ALTER TABLE mdm_uom RENAME COLUMN name_zh TO name;
ALTER TABLE mdm_uom DROP COLUMN name_en;

COMMENT ON COLUMN mdm_plant.name IS 'Plant 面向业务用户的名称；多语言显示由独立翻译能力扩展';
COMMENT ON COLUMN mdm_workshop.name IS 'Workshop 面向业务用户的名称；多语言显示由独立翻译能力扩展';
COMMENT ON COLUMN mdm_production_line.name IS 'ProductionLine 面向业务用户的名称；多语言显示由独立翻译能力扩展';
COMMENT ON COLUMN mdm_workstation.name IS 'Workstation 面向业务用户的名称；多语言显示由独立翻译能力扩展';
COMMENT ON COLUMN mdm_warehouse.name IS 'Warehouse 面向业务用户的名称；多语言显示由独立翻译能力扩展';
COMMENT ON COLUMN mdm_warehouse_area.name IS 'WarehouseArea 面向业务用户的名称；多语言显示由独立翻译能力扩展';
COMMENT ON COLUMN mdm_location_type.name IS 'LocationType 面向业务用户的名称；多语言显示由独立翻译能力扩展';
COMMENT ON COLUMN mdm_location.name IS 'Location 面向业务用户的名称；多语言显示由独立翻译能力扩展';
COMMENT ON COLUMN mdm_material_category.name IS '物料分类面向业务用户的名称；多语言显示由独立翻译能力扩展';
COMMENT ON COLUMN mdm_dimension.name IS '量纲面向业务用户的名称；多语言显示由独立翻译能力扩展';
COMMENT ON COLUMN mdm_uom_category.name IS '计量单位类别面向业务用户的名称；多语言显示由独立翻译能力扩展';
COMMENT ON COLUMN mdm_uom.name IS '计量单位面向业务用户的名称；多语言显示由独立翻译能力扩展';
