-- P01-S04 技术验证表，不属于正式主数据业务模型。
-- Schema 由 Flyway 的 create-schemas/default-schema 配置创建并管理。
CREATE TABLE technical_data_probe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    probe_key VARCHAR(120) NOT NULL,
    probe_value VARCHAR(500) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_by VARCHAR(128),
    updated_by VARCHAR(128),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_technical_data_probe_key UNIQUE (probe_key)
);

COMMENT ON TABLE technical_data_probe IS 'P01-S04 PostgreSQL、Flyway、MyBatis-Plus 技术验证表';
COMMENT ON COLUMN technical_data_probe.created_at IS 'UTC 创建时间';
COMMENT ON COLUMN technical_data_probe.updated_at IS 'UTC 最近更新时间';
COMMENT ON COLUMN technical_data_probe.version IS 'MyBatis-Plus 乐观锁版本号';
