spring:
  application:
    name: mom-iam-server
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:mom_platform}?currentSchema=${POSTGRES_SCHEMA:mom_iam}&tcpKeepAlive=${POSTGRES_TCP_KEEP_ALIVE:true}&ApplicationName=${POSTGRES_APPLICATION_NAME:mom-iam-server}}
    username: ${POSTGRES_USERNAME:mom_auth}
    password: ${POSTGRES_PASSWORD:}
    hikari:
      pool-name: ${POSTGRES_POOL_NAME:mom-iam-hikari}
      minimum-idle: ${POSTGRES_MINIMUM_IDLE:1}
      maximum-pool-size: ${POSTGRES_MAXIMUM_POOL_SIZE:5}
      connection-timeout: ${POSTGRES_CONNECTION_TIMEOUT:3000}
      validation-timeout: ${POSTGRES_VALIDATION_TIMEOUT:2000}
      leak-detection-threshold: ${POSTGRES_LEAK_DETECTION_THRESHOLD:0}
      connection-init-sql: SET TIME ZONE 'UTC'
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      connect-timeout: ${REDIS_CONNECT_TIMEOUT:2s}
      timeout: ${REDIS_COMMAND_TIMEOUT:2s}
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    create-schemas: true
    default-schema: ${POSTGRES_SCHEMA:mom_iam}
    schemas: ${POSTGRES_SCHEMA:mom_iam}
    locations: classpath:db/migration/iam
    validate-migration-naming: true
    clean-disabled: true
    baseline-on-migrate: false
